### ISSUE TITLE
Add watermarks to home page graphics

### ISSUE THREAD

**Issue by SamantaCasal** [XLabs/wormscan-ui#436]
### Description

Implement watermarks featuring the Wormholescan brand on all graphics displayed on the homepage. This will enhance brand visibility and protect our graphics from unauthorized use.

```[Steps]
### Tasks
- [ ] Design watermark and determine placement @Gpluv 
- [ ] Apply watermark design @giulianoconti 
- [ ]  Test on Desktop and mobile 
```
### Resources

Figma design here.

**Comment by Gpluv** [comment]
The Design is here: https://www.figma.com/file/kVuUyVjFFcRP55xHxHoKtH/WormholeScan?type=design&node-id=6179-11049&mode=design&t=ofNEVfzE930UMnjl-4

@giulianoconti 
@SamantaCasal

**Comment by SamantaCasal** [comment]
QA OK!

Mobile: 


https://github.com/XLabs/wormscan-ui/assets/69044575/d165238c-a5fb-4625-b73c-9259089ebc8b

Desktop


https://github.com/XLabs/wormscan-ui/assets/69044575/7277e501-2146-4221-aa70-cb7ee2cb3f60
